### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PCatinean** [pledra/odoo-product-configurator#101]
- [ ] enter the quantity of optional items during the product configuration - @PCatinean
- [x] Create a BOM with type Manufacture by default, instead of kit - @PCatinean
- [x] In the configuration wizard, use the first attribute value as the default value for required attributes - @PCatinean
- [ ] In the configuration wizard, allow to choose the product variants (if the mouse is an option, then allow to choose the color) - @PCatinean
- [x] Set the routing on the configurable template to be used when creating BOM - @ursais
- [x] Change the sales order line description format to match: - @PCatinean
[Base Product]
[Configuration Step]
[Attribute]: [Qty] - [Attribute Value] - $[Price]
- [x] Add the "Configure Product" button on the serial number screen - @PCatinean
- [x] Add a description field on the serial number. The product configuration wizard fills in the field with the same format as the SO line description. - @PCatinean
- [ ] In the configuration wizard of product A, allow to configure product B. Customer wants some recursivity here. @PCatinean
- [x] Create root menu for configurator @PCatinean

**Comment by max3903** [comment]
@bodedra

* Create a BOM with type Manufacture by default, instead of kit
* Set the routing on the configurable template to be used when creating BOM

**Comment by bodedra** [comment]
#103

**Comment by PCatinean** [comment]
@bodedra Thanks for the contribution, I will include the changes in the refactored version and publish the update after.

@max3903 I can take over the rest of the tasks from now on.

**Comment by andreampiovesana** [comment]
In the configuration wizard, use the first attribute value as the default
value for required attributes
Ok
1 I need the internal reference (not the barcode) for the product template
2 when i create a similar template using the action-duplicate, i need the
copy of the attributes+values
thanks in advance

Il 22/mag/2017 19:53, "Maxime Chambreuil" <notifications@github.com> ha
scritto:

**Comment by max3903** [comment]
Hi @PCatinean 

Some feedbacks after testing today:
- [x] Create a BOM with type Manufacture by default, instead of kit
- [x] In the configuration wizard, use the first attribute value as the default value for required attributes
- [x] Set the routing on the configurable template to be used when creating BOM
- [x] Create root menu for configurator
      I would copy the Attributes and Attribute Values menu items under the Configurator menu.

**Comment by max3903** [comment]
- [ ] Change the sales order line description format.
      The description is not using the template. Here is my template:
```
${template.name}
% for val in attribute_values:
<% attr_price = ('- $[%s]' % val.product_id.lst_price) if val.product_id else '' %> [${val.attribute_id.name}]: [Qty] - ${val.name} ${attr_price}
% endfor
```
and here is the output: `Home Building (2x3, Steel)`

- [ ] Add the "Configure Product" button on the serial number screen
      I need to select another produ
- [ ] Add a description field on the serial number. The product configuration wizard fills in the field with the same format as the SO line description.
      The field is there, but no content is copied from the product description.

**Comment by max3903** [comment]
@PCatinean

- [x] Change the sales order line description format.
      The description is not using the template. Here is my template:
```
${template.name}
% for val in attribute_values:
<% attr_price = ('- $[%s]' % val.product_id.lst_price) if val.product_id else '' %> [${val.attribute_id.name}]: [Qty] - ${val.name} ${attr_price}
% endfor
```
and here is the output: `Home Building (2x3, Steel)`

- [x] Add the "Configure Product" button on the serial number screen
      I need to select another product first to be able to start the configuration wizard. Otherwise I get:

```
The following field is invalid: Product
```

- [x] Add a description field on the serial number. The product configuration wizard fills in the field with the same format as the SO line description.
      Same as the sale order line. It looks like the description is not using the template.

**Comment by PCatinean** [comment]
@max3903 since the product is a required field for the lot object and the object needs to be saved before the wizard launches it needs a different approach. Most probably we will launch the wizard on create and present all templates (standard or configurable) and adjust accordingly.

Regarding the mako syntax if there's an error it will show up in the console and revert to the original naming. There's probably a syntax error, I will check.

**Comment by max3903** [comment]
- [x] In the configuration wizard, allow to choose the product variants (if the mouse is an option, then allow to choose the color)

**Comment by max3903** [comment]
@PCatinean 

- [ ] Name of the variants remain consistent all over, only description in sale.order.line and product lot use the mako templating system.
* The configuration wizard can be launched from the configurable template and the description should be included in the "Description for Quotations" field.
* The product variant name "T-shirt (red, XS)" is not added to the description of the configurable variant.
- [x] Lot configurator now has the same functionalities as sale (meaning they both use the mrp version)
- [x] Subconfigurable products have been added and a new configuration process is launched in the same wizard. Returns to the parent wizard when the subconfigurable product process ends.
- [ ] The attribute value related variants from the subconfigurable products are added to the main bom.
* The subconfigured product is not added to the configurable variant description and to its BOM.

Questions:
* What is the variable name to use in the template for the quantity?

**Comment by wujenne2** [comment]
Results from testing: 

- WARNING product_config_odoo_9 openerp.models: product.configurator.read() with unknown field '__attribute_qty-2' message logged when configuring product.
- When using two levels of recursion, only the subconfigurable products generate BOMs.  i.e. when the "Home Building" template has subconfigurable "Rooftop" product which has the subconfigurable "Ceiling Fixture" product, only a Rooftop and Ceiling Fixture BOM are generated.
- When a configurable template has two subconfigurable products, it creates all three BOMs, but does not successfully generate all the components in the first subconfigurable product's BOM. Also, the wizard does not show the menu options for the second subconfigurable product. i.e. When "Home Building" template has subconfigurable Rooftop and Ceiling Fixtures products, Rooftop BOM generatedoes not have components and the wizard for Ceiling Fixture does not show the dropdown menu for the attribute values.
- "Duplicate" Action for Configurable Templates doesn't work - puts the same form in edit mode.
- Sales Order description line and description on serial number does not match template.
- 2017-06-13 19:26:16,183 26369 ERROR product_config_odoo_9 openerp.addons.product_configurator.models.product: Error while calculating mako product name: Basic Home (10x12, 3x3, Renaissance) appears in log when creating product variant.

**Comment by max3903** [comment]
@PCatinean 

- [ ] The configuration wizard creates duplicate of the subconfigurable products (same options, same quantities --> same BOM).
- [ ] I tried using `${quantity}` and `${val.quantity}` in my template. None of them works.
- [x] I am not able to select the configurable variant on a manufacturing order and a sales order.

**Comment by max3903** [comment]
New features:

- [x] Add a "Configure Product" button on the manufacturing order
- [x] Add the description based on the template in the description_sale field of the product
